name: Test full

on:
  push:
    branches: ["ci/decouple-testing"]  # FIXME

jobs:
  cpu:
    # Supported keywords for jobs that call a reusable workflow:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
    uses: PyTorchLightning/pytorch-lightning/.github/workflows/_test.yml@ci/decouple-testing  # FIXME
