name: Test slow

on:
  push:
    branches: ["ci/decouple-testing"]  # FIXME

concurrency:  # FIXME
  group: decouple-testing-slow
  cancel-in-progress: true

jobs:
  slow:
    # Supported keywords for jobs that call a reusable workflow:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
    uses: PyTorchLightning/pytorch-lightning/.github/workflows/_test.yml@ci/decouple-testing  # FIXME
    with:
      test-tag: 'slow'
      test-envs: 'PL_RUN_SLOW_TESTS=1'
      timeout-minutes: 20
