name: Create Legacy Ckpts

on:
  workflow_dispatch:
    inputs:
      push_to_s3:
        description: 'Push generated checkpoints to S3'
        required: false
        type: boolean

jobs:
  create-legacy-ckpts:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./legacy
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1

    - name: Generate checkpoints
      run: |
        # while IFS= read -r line; do
        #     bash generate_checkpoints.sh $line
        # done <<< $(cat back-compatible-versions.txt)
        bash generate_checkpoints.sh 1.5.0 1.5.1
        zip -r checkpoints.zip checkpoints

    - name: Upload checkpoints as GitHub Actions' artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkpoints-${{ github.sha }}
        path: legacy/checkpoints/
      if: always()

    - name: Upload checkpoints to S3
      run: |
        # Upload checkpoints without archiving.
        # aws s3 sync checkpoints/ s3://pl-public-data/legacy/checkpoints/
        # Upload checkpoints archived in a zip which will be used in our tests.
        aws s3 cp checkpoints.zip s3://pl-public-data/legacy/ --acl public-read
      if: ${{ github.event.inputs.push_to_s3 == 'true' }}
