name: Create Legacy Ckpts

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
# on:
#   workflow_dispatch:
on: push  # FIXME

jobs:
  create-legacy-ckpts:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1

    - name: Generate checkpoints
      run: |
        while IFS= read -r line; do
            bash legacy/generate_checkpoints.sh $line
        done <<< $(cat legacy/back-compatible-versions.txt)
        zip -r legacy/checkpoints.zip legacy/checkpoints

    - name: Upload checkpoints as GitHub Actions' artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkpoints-${{ github.sha }}
        path: legacy/checkpoints.zip
      if: always()

    - name: Upload checkpoints to S3
      run: |
        # Upload checkpoints without archiving.
        # aws s3 sync legacy/checkpoints/ s3://pl-public-data/legacy/checkpoints/
        # Upload checkpoints archived in a zip.
        # aws s3 cp legacy/checkpoints.zip s3://pl-public-data/legacy/ --acl public-read
